version: '3.8'
services:
  redis:
    image: redis:7
    container_name: shakers-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: shakers-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_config:/etc/prometheus   # contains prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: shakers-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards:ro